---
title: "Datenschutzerklärung"
---

Die Betreiber dieser Seiten nehmen den Schutz Ihrer persönlichen Daten sehr ernst. Wir behandeln Ihre personenbezogenen Daten vertraulich und entsprechend der gesetzlichen Datenschutzvorschriften sowie dieser Datenschutzerklärung. 

Die Nutzung unserer Website ist in der Regel ohne Angabe personenbezogener Daten möglich. Soweit auf unseren Seiten personenbezogene Daten erhoben werden, erfolgt dies, soweit möglich, stets auf freiwilliger Basis. Diese Daten werden ohne Ihre ausdrückliche Zustimmung nicht an Dritte weitergegeben. Wir weisen darauf hin, dass die Datenübertragung im Internet (z.B. bei der Kommunikation per E-Mail) Sicherheitslücken aufweisen kann. Ein lückenloser Schutz der Daten vor dem Zugriff durch Dritte ist nicht möglich.


* Auf dieser Seite werden keine Cookies gesetzt und die Seite beinhaltet keine Werbung
* Die Seite ist auf [Netlify](https://netlify.app/) gehosted. [Hier](https://www.netlify.com/gdpr-ccpa/) sind Informationen zum Datenschutz bei Netlify zu finden.

<!-- * Die Kommentarfunktion ist über eine Einbettung von [Github utterances](https://github.com/utterance/utterances) realisiert. Inwieweit dort personenbezogene Daten erhoben werden entnehmen Sie bitte der [Projektwebseite](https://github.com/utterance/utterances). -->

* Verantwortlich für den Datenschutz:
  * Sebastian Gerdes
    * Adresse: Talstraße 7, 01099 Dresden
    * E-Mail: dresden-solar(at)posteo.de

