---
title: "Mitmachen"
---

## So kannst Du Dich beteiligen
* Ein guter Startpunkt ist die Teilnahme an den regelmäßigen (ca. einmal monatlichen) Plena - in diesen Treffen tauschen wir uns über die Projektfortschritte aus
* Zusätzlich treffen sich die Mitglieder der einzelnen Arbeitsgruppen je nach Bedarf
* Ein weitere Beteiligungsmöglichkeit ist die Teilnahme an einer Aktion - zum Beispiel Demonstrationen, Klimastreiks und Ähnliches!

Möchtest Du mitmachen, schreibe am besten eine E-Mail an:  
**dresden(at)healthforfuture(punkt)de!**

Um auf dem Laufenden zu bleiben, lasse Dich gern auf unsere Mailingliste setzen - dazu schreibst Du am besten ebenfalls eine E-Mail an dresden(at)healthforfuture(punkt)de!

Finanzielle Unterstützung unserer Arbeit ist [hier](https://healthforfuture.de/spenden/) möglich!


<!-- ## Nächste Treffen -->

<!-- | Wann                      | Was                   | Wo                     | -->
<!-- |---------------------------|-----------------------|------------------------| -->
<!-- | 7.11.2024, 18:30 Uhr | AG Ernährung | Zoom-Link auf Anfrage | -->
<!-- | 26.11.2024, 19:30 Uhr | Plenum hybrid | Impact Loft, Theaterstraße 4, 1. OG, Zoom-Link auf Anfrage | -->
<!-- : {tbl-colwidths="[30,30,40]"} -->

<!-- | 10.7.2024, 19:30 Uhr | AG Koordination  | Voraussichtlich AHA Café | -->
<!-- | 30.7.2024, 14:00 Uhr | AG Nachhaltige Praxis  | Auf Anfrage | -->
<!-- | 7.3.2024, mittags | Infostand AG Ernährung | Kantine "Caruso" am Uniklinikum -->
<!-- | 1.3.2024 | Treffen der AG Lehre | ausstehend -->
<!-- | 4.3.2024, 19:00 Uhr | Treffen der AG Ernährung | Impact Loft Theaterstraße 4, 1. OG | -->