---
title: "Workshops und Vorträge"
---

Wir bieten Workshops und Vorträge zu unterschiedlichsten Themen an. Neben den unten aufgeführten sind nach Absprache auch weitere oder spezifisch auf Deine Gruppe / Verein / Partei zugeschnittene Veranstaltungen möglich. Gern bieten wir auch Workshops oder Vorträge in Schulen an! Bei Interesse oder auch bei Fragen zu den genauen Inhalten schreibe uns gerne an unter **dresden(at)healthforfuture(punkt)de**!

Wir freuen uns über Ihr Interesse an unseren Vorträgen und bitten um Verständnis, dass wir ein Honorar erheben. Die genaue Höhe des Honorars kann jedoch in einem persönlichen Gespräch gemeinsam festgelegt werden.
  
### Bestehende Workshops und Vorträge
* Einführung Planetary Health
* Einführung Klima und Gesundheit
* Aktivismus / Health for Future
* Planetary Health Diet (klimagerechte, gesunde Ernährung)
* Nachhaltiges Gesundheitswesen
* Nachhaltige Praxis
* Klimasensible Gesundheitsberatung
* Hitze und Gesundheit
* Frauengesundheit in der Klimakrise
* Allergien und Klimakrise