---
title: "Arbeitsgruppe Divestment"
---

## Was hat die Klimakrise mit dem Ärztlichen Versorgungswerk zu tun?
Das Ziel des Pariser Klimaabkommens, die Erderwärmung auf unter 2° C - besser 1,5° C - gegenüber dem vorindustriellen Zeiten zu begrenzen, erfordert eine weitgehende Dekarbonisierung der Weltwirtschaft. 

Vor diesem Hintergrund entstand etwa 2012 eine globale gesellschaftliche Divestment-Bewegung, die den Abzug von Investitionen in fossile Brennstoffunternehmen und die Reinvestition in klimafreundliche Anlagen fordert.

Für [KLUG](https://www.klimawandel-gesundheit.de/) und [Health for Future](https://healthforfuture.de/) ist Divestment im Hinblick auf die ärztlichen Versorgungswerke ein zentrales Handlungsfeld. 

Im Ergebnis eines intensiven Gesprächsprozesses mit Vertretern der Sächsischen Landesärztekammmer und der Sächischen Ärzteversorgung (SÄV) kam es 2021 zur Vorlage eines [„Positionspapieres zur nachhaltigen Ausrichtung des Geschäftsbetriebes der Sächsischen Ärzteversorgung“](https://www.saev.de/fileadmin/user_upload/downloads/publikationen/SAEV_Nachhaltigkeitsstrategie.pdf). In diesem bekennt sich die SÄV ausdrücklich zu den Zielen des Pariser Klimaschutzabkommens. 

Ziel unserer AG ist es, diesen Prozess weiterhin konstruktiv-kritisch zu begleiten.

Kontakt: dresden(at)healthforfuture(punkt)de

## Links
* [https://www.saev.de/ueber-uns/nachhaltigkeit.html](https://www.saev.de/ueber-uns/nachhaltigkeit.html)
* [https://www.klimawandel-gesundheit.de/handlungsfelder-und-projekte/divestment/](https://www.klimawandel-gesundheit.de/handlungsfelder-und-projekte/divestment/)
