---
title: "Arbeitsgruppe Ernährung"
---

In der AG Ernährung beschäftigen wir uns mit der 2019 von der internationalen Wissenschaftlerkommission EAT-Lancet entwickelten Planetary Health Diet, eine Ernährungsempfehlung, die Gesundheit und Klimaschutz gleichermaßen beachtet und optimal verbindet. Sie würde es ermöglichen, dass auch 10 Milliarden Menschen sich gesund ernähren könnten, ohne die ökologischen Belastungsgrenzen der Erde zu überschreiten. 

Wir setzen uns dafür ein, dass diese Ernährunsgempfehlung mehr Beachtung findet, stellen sie in verschiedenen Settings mittels Vorträgen vor, nehmen an Aktionen zur Ernährungswende teil und sind in Kontakt mit Dresdner Krankenhäusern, um dort die Essensversorgung für Patienten und Mitarbeiter entsprechend positiv zu verändern.  Es besteht ein reger Austausch mit der bundesweiten Ernährungs-AG, welche ein Positionspapier zum Thema veröffentlich hat, und bundesweite Aktionen koordiniert, an welchen wir uns als Ortsgruppe beteiligen können.

Wenn du Lust hast mitzumachen, melde dich gern. Wir treffen uns in unterschiedlichen Abständen, etwa alle 1-2 Monate, in der Neustadt oder online.

Zum Weiterlesen: [Food for Future: Ernährungswende für individuelle und planetare Gesundheit – Positionspapier](/arbeitsgruppen/files/20230121_H4F_Positionspapier_Ernaehrungswende.pdf)

