---
title: "Arbeitsgruppe Koordination"
---

Findest du die Arbeit von Health for Future Dresden gut und fragst dich, wie du die Ortsgruppe am besten unterstützen kannst?

Organisierst du gerne oder hast Freude an der Kommunikation und Vernetzung?

Dann bist du in der AG Koordination genau richtig!

Die AG Koordination organisiert, dass Health for Future Dresden neue Mitglieder gewinnt, und dass alle Mitglieder möglichst wirksam und reibungslos arbeiten können. 

Dafür kümmern wir uns um folgende Aufgaben:

* wir organisieren die regelmäßigen Ortsgruppentreffen
* wir veranstalten Onboardings
* wir binden Neumitglieder ein
* wir betreuen den E-Mail-Account
* wir leiten Informationen in die Ortsgruppe weiter
* wir sind die Ansprechpartner*innen für kooperierende Organisationen
* wir entwickeln neue Ideen für die Organisation und die Arbeit der Ortsgruppe

Wir treffen uns ca. einmal im Monat, meist dienstags zum Frühstück.

Dich erwartet ein sehr nettes Team und eine von Wertschätzung geprägte Tätigkeit.
Wir würden uns sehr über deine Unterstützung freuen.

Ansprechpartnerin: Sina Lehmann, Kontakt: dresden(at)healthforfuture(punkt)de