---
title: "Arbeitsgruppe Politikergespräche"
---

Die AG Politikergespräche wurde im Vorfeld der Bundestagswahl 2021 gegründet, um zur Wahl aufgestellte Abgeordnete verschiedener Parteien zu kontaktieren und in Gesprächen über die vielzähligen gesundheitlichen Folgen der Klimakrise aufzuklären. Unsere Erfahrungen waren durchweg positiv, da sich auch diejenigen erreichen ließen, denen Umweltschutz allein kein wichtiges Anliegen war, die sich aber für das Argument des Gesundheitsschutzes zumindest etwas offener zeigten.

Auch über die Bundestagswahl hinaus ist es wichtig, mit Politikern in Kontakt zu bleiben und unsere Expertise zu nutzen, politische Entscheidungsträger über die Zusammenhänge von Klima und Gesundheit zu informieren und sie damit zu mehr Klimaschutz zu motivieren.

Ein aktuelles Projekt ist die Kontaktaufnahme mit sächsischen Bundestagsabgeordneten, die im Ausschuss für Ernährung und Landwirtschaft an der Entwicklung der sogenannten „Ernährungsstrategie für Deutschland“ beteiligt sind. Unser Ziel ist es auch hier, unsere Expertise einzubringen und uns für eine gesündere und gleichzeitig klimaverträglichere Ernährung einzusetzen.

Unsere Treffen finden also projektbezogen statt, das heißt, dass es auch möglich ist, sich nur mal vorübergehend für eine Aktion zu engagieren. Wir treffen uns überwiegend online via Zoom. Wer Lust hat, sich an den Politikergesprächen zu beteiligen, kann sich gern jederzeit melden.