---
title: "Code Snippets"
execute: 
  eval: false
---

## Neuen Post erstellen
```{r}
create_post <- function(post_title) {
  ll <- readLines('_additional/sample_post.qmd')
  ll[2] <- paste('title: \"', post_title, "\"", sep = '')
  ll[3] <- paste('date: \"', Sys.Date(), "\"", sep = '')
  file_name <- paste0('posts/', Sys.Date(), '_',
                     janitor::make_clean_names(post_title), 
                     '.qmd')
  writeLines(ll, con = file_name)
  file.edit(file_name)
}
```

```{r}
create_post(post_title = 'Herzlichen Dank - Gemeinsam für Klima und Gesundheit!')
```

## Seite neu zusammenstellen (=rendern)
```{r}
library('fs')
backup_dir <- 'additional/backup/' 
source_dir <- '_site/'
dir_create(backup_dir)
files_to_rescue <- paste0(source_dir, c('site_libs/')) #, '_site/.gitignore')
file_move(files_to_rescue, backup_dir)
file_delete('_site/')
dir_create(source_dir)
file_move(paste0(backup_dir, 'site_libs/'), source_dir)
file_delete(backup_dir)
system('quarto render')
```

```{r}
library('magick')
library('fs')

change_image_dimensions <- Vectorize(
  function(file_name_in, new_pixel_width = 200) {
    file_name_out <- paste0(path_ext_remove(file_name_in), '_small.png')
    my_image <- image_read(file_name_in)
    my_image_small <- 
      image_resize(my_image, 
                   geometry = geometry_size_pixels(width = new_pixel_width))
    image_write(my_image_small, path = file_name_out)
    return(my_image_small)
  })

files <- c('images/links_logos/KLUG_Logo-150.png', 
           'images/links_logos/fff_dresden.webp', 
           'images/links_logos/h4f-logo.png')

files <- c('images/links_logos/logo_for_future.png')

change_image_dimensions(files)

```
