---
title: "9.11.2023: Vorträge zu Planetary Health diet in der Berufsakademie"
date: "2023-10-16"
---

Gern möchten wir auf eine Veranstaltung mit folgenden Vorträgen aufmerksam machen:

* *Von Bratwurst und Brokkoli: Unser Essen, unser Planet, unsere Verantwortung. Wie unsere Ernährungssysteme die Gesundheit der Erde bedrohen, und was wir jetzt verändern können, ohne dabei den Appetit zu verlieren*: Herrn Dr. Jörg Schmid, Wissenschaftlicher Mitarbeiter Ernährung und Planetary Health, KLUG - Deutsche Allianz Klimawandel und Gesundheit e.V., 40 Minuten + 5 Minuten Fragerunde
* *Planetary Health Diet - Den Schutz der Gesundheit des Menschen und des Planeten gleichermaßen im eigenen Menüplan praktisch umsetzen & wie innovative (regionale) Produkte bei der Ernährungstransformation unterstützen können*: Frau Dr. Madlen Stimming, Beratung für regionale Wertschöpfungsketten, AgiL – Sächsische Agentur für Regionale Lebensmittel, 40 Minuten + 5 Minuten Fragerunde

# Die wichtigen Ws:

* Wann: 9.11. November 2023, ab 15:30 Uhr
* Wo: im Raum 3.015 Berufsakademie Dresden, Hans-Grundig-Str. 25

